openpgp: Tweak lifetime of filter function's argument.
  - Previously, the filter operated on references with the lifetime 'a
    only, which is the lifetime associated with the Cert the TSK
    object references.  Change the signature to take a reference with
    an anonymous lifetime instead.

  - This makes the filter more general, but it can no longer rely on
    the fact that the references are live for 'a.  However, the
    function is a Fn, not a FnMut, and returns a bool, so the function
    cannot store the reference anywhere, so this shouldn't make a
    difference in practice.

  - Annoyingly, there is a wrinkle.  If a closure bound to an
    identifier is given to TSK::set_filter, the Rust compiler
    incorrectly (or over eagerly?) specializes the function in a way
    that it doesn't match the callback's prototype:

        error[E0308]: mismatched types
           --> openpgp/src/serialize/cert.rs:946:16
            |
        946 |         check!(tsk_0.as_tsk().set_filter(no_secrets),
            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
            |

            = note: expected trait `for<'a> Fn<(&'a packet::Key<packet::key::SecretParts, packet::key::UnspecifiedRole>,)>`
                       found trait `Fn<(&packet::Key<packet::key::SecretParts, packet::key::UnspecifiedRole>,)>`
        note: this closure does not fulfill the lifetime requirements
           --> openpgp/src/serialize/cert.rs:940:26
            |
        940 |         let no_secrets = |_| false;
            |                          ^^^
        note: the lifetime requirement is introduced here
           --> openpgp/src/serialize/cert.rs:318:23
            |
        318 |         where P: 'a + Fn(&key::UnspecifiedSecret) -> bool
            |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        error: implementation of `FnOnce` is not general enough
           --> openpgp/src/serialize/cert.rs:946:16
            |
        946 |         check!(tsk_0.as_tsk().set_filter(no_secrets),
            |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `FnOnce` is not general enough
            |
            = note: closure with signature `fn(&'2 packet::Key<packet::key::SecretParts, packet::key::UnspecifiedRole>) -> bool` must implement `FnOnce<(&'1 packet::Key<packet::key::SecretParts, packet::key::UnspecifiedRole>,)>`, for any lifetime `'1`...
            = note: ...but it actually implements `FnOnce<(&'2 packet::Key<packet::key::SecretParts, packet::key::UnspecifiedRole>,)>`, for some specific lifetime `'2`

    This is easily fixed by providing a partial type for the
    callback's argument.  This commit includes a tweak for our test.