openpgp: Fix returning cached errors.
  - There is a wrinkle with caching parsed user IDs.  You can return a
    Result<&_> to the cached value, but the error is owned.  Now,
    because we use anyhow::Error, which does not implement Clone, we
    cannot clone the error.  Previously, we folded all errors to
    Error::InvalidArgument, but one downstream user was sensitive
    enough to complain about the wrong error being returned.

  - Just cache successes!  If parsing fails, re-do it for every
    caller.  I'm pretty sure that is what OnceCell::get_or_try_init
    does.

  - This wouldn't be an issue if we would not use anyhow::Error.
    Then, we'd have to explicitly account for the unicode error in our
    Error enum, but, we could make it implement clone!